

export const ApiKeyManagementTableData = [
  {
    user: { value: "John Doe", show: false },
    details: { value: "Some details", show: false },
    time: { value: "12:00 PM", show: false },
    activity: { value: "Logged in", show: false },
    status: { value: "true", show: false },
    emial: { value: "john@example.com", show: false },
    joinedOn: { value: "2025-07-11", show: false },
    reports: { value: "2", show: false },
    pets: { value: "Dog", show: false },
    petsName: { value: "Buddy", show: false },
    petStatus: { value: "Healthy", show: false },
    breed: { value: "Labrador", show: false },
    petColor: { value: "Brown", show: false },
    location: { value: "New York", show: false },
    reportedBy: { value: "Admin", show: false },
    reportedOn: { value: "2025-07-11", show: false },
    date: { value: "2025-07-11", show: false },
    donorName: { value: "Jane Smith", show: false },
    amount: { value: "$50", show: false },
    campaign: { value: "Save the pets", show: false },
    type: { value: "One-time", show: false },
    donorstatus: { value: "Confirmed", show: false },
    totalAmmount: { value: "12345", show: false },
    lastDonation: { value: "jul 6,2025", show: false },
    recurring: { value: "12345", show: false },
    campaignName: { value: "12345", show: false },
    targetAmount: { value: "12345", show: false },
    raisedSoFar: { value: "12345", show: false },
    donors: { value: "12345", show: false },
    campaignStatus: { value: "12345", show: false },
    progress: { value: "12345", show: false },
    service:{value: "Sarah Jhon", show : true},
    key:{value: "Ai**********" , show : true},
    lastUser : {value : "Today, 10:24 AM", show: true},
    deleteIcon: {value : " Delete" , show : true}
  },
  {
    user: { value: "John Doe", show: false },
    details: { value: "Some details", show: false },
    time: { value: "12:00 PM", show: false },
    activity: { value: "Logged in", show: false },
    status: { value: "true", show: false },
    emial: { value: "john@example.com", show: false },
    joinedOn: { value: "2025-07-11", show: false },
    reports: { value: "2", show: false },
    pets: { value: "Dog", show: false },
    petsName: { value: "Buddy", show: false },
    petStatus: { value: "Healthy", show: false },
    breed: { value: "Labrador", show: false },
    petColor: { value: "Brown", show: false },
    location: { value: "New York", show: false },
    reportedBy: { value: "Admin", show: false },
    reportedOn: { value: "2025-07-11", show: false },
    date: { value: "2025-07-11", show: false },
    donorName: { value: "Jane Smith", show: false },
    amount: { value: "$50", show: false },
    campaign: { value: "Save the pets", show: false },
    type: { value: "One-time", show: false },
    donorstatus: { value: "Confirmed", show: false },
    totalAmmount: { value: "12345", show: false },
    lastDonation: { value: "jul 6,2025", show: false },
    recurring: { value: "12345", show: false },
    campaignName: { value: "12345", show: false },
    targetAmount: { value: "12345", show: false },
    raisedSoFar: { value: "12345", show: false },
    donors: { value: "12345", show: false },
    campaignStatus: { value: "12345", show: false },
    progress: { value: "12345", show: false },
    service:{value: "Sarah Jhon", show : true},
    key:{value: "Ai**********" , show : true},
    lastUser : {value : "Today, 10:24 AM", show: true},
    deleteIcon: {value : " Delete" , show : true}
  },
  {
    user: { value: "John Doe", show: false },
    details: { value: "Some details", show: false },
    time: { value: "12:00 PM", show: false },
    activity: { value: "Logged in", show: false },
    status: { value: "true", show: false },
    emial: { value: "john@example.com", show: false },
    joinedOn: { value: "2025-07-11", show: false },
    reports: { value: "2", show: false },
    pets: { value: "Dog", show: false },
    petsName: { value: "Buddy", show: false },
    petStatus: { value: "Healthy", show: false },
    breed: { value: "Labrador", show: false },
    petColor: { value: "Brown", show: false },
    location: { value: "New York", show: false },
    reportedBy: { value: "Admin", show: false },
    reportedOn: { value: "2025-07-11", show: false },
    date: { value: "2025-07-11", show: false },
    donorName: { value: "Jane Smith", show: false },
    amount: { value: "$50", show: false },
    campaign: { value: "Save the pets", show: false },
    type: { value: "One-time", show: false },
    donorstatus: { value: "Confirmed", show: false },
    totalAmmount: { value: "12345", show: false },
    lastDonation: { value: "jul 6,2025", show: false },
    recurring: { value: "12345", show: false },
    campaignName: { value: "12345", show: false },
    targetAmount: { value: "12345", show: false },
    raisedSoFar: { value: "12345", show: false },
    donors: { value: "12345", show: false },
    campaignStatus: { value: "12345", show: false },
    progress: { value: "12345", show: false },
    service:{value: "Sarah Jhon", show : true},
    key:{value: "Ai**********" , show : true},
    lastUser : {value : "Today, 10:24 AM", show: true},
    deleteIcon: {value : " Delete" , show : true}
  },
  {
    user: { value: "John Doe", show: false },
    details: { value: "Some details", show: false },
    time: { value: "12:00 PM", show: false },
    activity: { value: "Logged in", show: false },
    status: { value: "true", show: false },
    emial: { value: "john@example.com", show: false },
    joinedOn: { value: "2025-07-11", show: false },
    reports: { value: "2", show: false },
    pets: { value: "Dog", show: false },
    petsName: { value: "Buddy", show: false },
    petStatus: { value: "Healthy", show: false },
    breed: { value: "Labrador", show: false },
    petColor: { value: "Brown", show: false },
    location: { value: "New York", show: false },
    reportedBy: { value: "Admin", show: false },
    reportedOn: { value: "2025-07-11", show: false },
    date: { value: "2025-07-11", show: false },
    donorName: { value: "Jane Smith", show: false },
    amount: { value: "$50", show: false },
    campaign: { value: "Save the pets", show: false },
    type: { value: "One-time", show: false },
    donorstatus: { value: "Confirmed", show: false },
    totalAmmount: { value: "12345", show: false },
    lastDonation: { value: "jul 6,2025", show: false },
    recurring: { value: "12345", show: false },
    campaignName: { value: "12345", show: false },
    targetAmount: { value: "12345", show: false },
    raisedSoFar: { value: "12345", show: false },
    donors: { value: "12345", show: false },
    campaignStatus: { value: "12345", show: false },
    progress: { value: "12345", show: false },
    service:{value: "Sarah Jhon", show : true},
    key:{value: "Ai**********" , show : true},
    lastUser : {value : "Today, 10:24 AM", show: true},
    deleteIcon: {value : " Delete" , show : true}
  },
]

export default ApiKeyManagementTableData
