import Profileimg from "../assets/Images/profile.png"; 

const DahboardTableData  = [
  {
    user: { value: "John Doe", show: true },
    userImg: Profileimg,
    details: { value: "Some details", show: true },
    time: { value: "12:00 PM", show: true },
    activity: { value: "Logged in", show: true },
    status: { value: "true", show: true },
    emial: { value: "john@example.com", show: false },
    joinedOn: { value: "2025-07-11", show: false },
    reports: { value: "2", show: false },
    pets: { value: "Dog", show: false },
    petsName: { value: "Buddy", show: false },
    petStatus: { value: "Healthy", show: false },
    breed: { value: "Labrador", show: false },
    petColor: { value: "Brown", show: false },
    location: { value: "New York", show: false },
    reportedBy: { value: "Admin", show: false },
    reportedOn: { value: "2025-07-11", show: false },
    date: { value: "2025-07-11", show: false },
    donorName: { value: "Jane Smith", show: false },
    amount: { value: "$50", show: false },
    campaign: { value: "Save the pets", show: false },
    type: { value: "One-time", show: false },
    donorstatus: { value: "Confirmed", show: false },
    totalAmmount: { value: "12345", show: false },
    lastDonation: { value: "jul 6,2025", show: false },
    recurring: { value: "12345", show: false },
    campaignName: { value: "12345", show: false },
    targetAmount: { value: "12345", show: false },
    raisedSoFar: { value: "12345", show: false },
    donors: { value: "12345", show: false },
    campaignStatus: { value: "12345", show: false },
    progress: { value: "12345", show: false },
  },
  {
    user: { value: "Jane Smith", show: true },
    userImg: Profileimg,
    details: { value: "Updated profile", show: true },
    time: { value: "1:15 PM", show: true },
    activity: { value: "Profile update", show: true },
    status: { value: "false", show: true },
    emial: { value: "jane@example.com", show: false },
    joinedOn: { value: "2025-07-10", show: false },
    reports: { value: "3", show: false },
    pets: { value: "Cat", show: false },
    petsName: { value: "Milo", show: false },
    petStatus: { value: "Healthy", show: false },
    breed: { value: "Siamese", show: false },
    petColor: { value: "White", show: false },
    location: { value: "Chicago", show: false },
    reportedBy: { value: "User", show: false },
    reportedOn: { value: "2025-07-10", show: false },
    date: { value: "2025-07-10", show: false },
    donorName: { value: "Alex Johnson", show: false },
    amount: { value: "$75", show: false },
    campaign: { value: "Feed the cats", show: false },
    type: { value: "Recurring", show: false },
    donorstatus: { value: "Pending", show: false },
    totalAmmount: { value: "12345", show: false },
    lastDonation: { value: "jul 6,2025", show: false },
    recurring: { value: "12345", show: false },
    campaignName: { value: "12345", show: false },
    targetAmount: { value: "12345", show: false },
    raisedSoFar: { value: "12345", show: false },
    donors: { value: "12345", show: false },
    campaignStatus: { value: "12345", show: false },
    progress: { value: "12345", show: false },
  },
  {
    user: { value: "Alex Johnson", show: true },
    userImg: Profileimg,
    details: { value: "Uploaded document", show: true },
    time: { value: "2:30 PM", show: true },
    activity: { value: "File upload", show: true },
    status: { value: "true", show: true },
    emial: { value: "alex@example.com", show: false },
    joinedOn: { value: "2025-07-09", show: false },
    reports: { value: "0", show: false },
    pets: { value: "Bird", show: false },
    petsName: { value: "Kiwi", show: false },
    petStatus: { value: "Injured", show: false },
    breed: { value: "Parrot", show: false },
    petColor: { value: "Green", show: false },
    location: { value: "Los Angeles", show: false },
    reportedBy: { value: "Moderator", show: false },
    reportedOn: { value: "2025-07-09", show: false },
    date: { value: "2025-07-09", show: false },
    donorName: { value: "Emily Davis", show: false },
    amount: { value: "$100", show: false },
    campaign: { value: "Save injured birds", show: false },
    type: { value: "One-time", show: false },
    donorstatus: { value: "Confirmed", show: false },
    totalAmmount: { value: "12345", show: false },
    lastDonation: { value: "jul 6,2025", show: false },
    recurring: { value: "12345", show: false },
    campaignName: { value: "12345", show: false },
    targetAmount: { value: "12345", show: false },
    raisedSoFar: { value: "12345", show: false },
    donors: { value: "12345", show: false },
    campaignStatus: { value: "12345", show: false },
    progress: { value: "12345", show: false },
  },
  {
    user: { value: "Emily Davis", show: true },
    userImg: Profileimg,
    details: { value: "Deleted post", show: true },
    time: { value: "3:45 PM", show: true },
    activity: { value: "Post deletion", show: true },
    status: { value: "false", show: true },
    emial: { value: "emily@example.com", show: false },
    joinedOn: { value: "2025-07-08", show: false },
    reports: { value: "1", show: false },
    pets: { value: "Rabbit", show: false },
    petsName: { value: "Snowy", show: false },
    petStatus: { value: "Healthy", show: false },
    breed: { value: "Angora", show: false },
    petColor: { value: "White", show: false },
    location: { value: "Houston", show: false },
    reportedBy: { value: "Admin", show: false },
    reportedOn: { value: "2025-07-08", show: false },
    date: { value: "2025-07-08", show: false },
    donorName: { value: "Michael Brown", show: false },
    amount: { value: "$60", show: false },
    campaign: { value: "Rabbit care", show: false },
    type: { value: "Monthly", show: false },
    donorstatus: { value: "Confirmed", show: false },
    totalAmmount: { value: "12345", show: false },
    lastDonation: { value: "jul 6,2025", show: false },
    recurring: { value: "12345", show: false },
    campaignName: { value: "12345", show: false },
    targetAmount: { value: "12345", show: false },
    raisedSoFar: { value: "12345", show: false },
    donors: { value: "12345", show: false },
    campaignStatus: { value: "12345", show: false },
    progress: { value: "12345", show: false },
  },
  {
    user: { value: "Michael Brown", show: true },
    userImg: Profileimg,
    details: { value: "Generated report", show: true },
    time: { value: "4:00 PM", show: true },
    activity: { value: "Report generation", show: true },
    status: { value: "true", show: true },
    emial: { value: "michael@example.com", show: false },
    joinedOn: { value: "2025-07-07", show: false },
    reports: { value: "5", show: false },
    pets: { value: "Horse", show: false },
    petsName: { value: "Star", show: false },
    petStatus: { value: "Healthy", show: false },
    breed: { value: "Arabian", show: false },
    petColor: { value: "Black", show: false },
    location: { value: "Dallas", show: false },
    reportedBy: { value: "Moderator", show: false },
    reportedOn: { value: "2025-07-07", show: false },
    date: { value: "2025-07-07", show: false },
    donorName: { value: "John Doe", show: false },
    amount: { value: "$120", show: false },
    campaign: { value: "Horse shelter", show: false },
    type: { value: "Yearly", show: false },
    donorstatus: { value: "Confirmed", show: false },
    totalAmmount: { value: "12345", show: false },
    lastDonation: { value: "jul 6,2025", show: false },
    recurring: { value: "12345", show: false },
    campaignName: { value: "12345", show: false },
    targetAmount: { value: "12345", show: false },
    raisedSoFar: { value: "12345", show: false },
    donors: { value: "12345", show: false },
    campaignStatus: { value: "12345", show: false },
    progress: { value: "12345", show: false },
  },
 
];

export default DahboardTableData;