

const DonorDirectryTableData = [
  {
    user: { value: "John Doe", show: false },
    details: { value: "Some details", show: false },
    time: { value: "12:00 PM", show: false },
    activity: { value: "Logged in", show: false },
    status: { value: "true", show: false },
    emial: { value: "john@example.com", show: true },
    joinedOn: { value: "2025-07-11", show: false },
    reports: { value: "2", show: false },
    recentReports: { value: "2 hours ago", show: false },
    pets: { value: "Dog", show: false },
    petsName: { value: "Buddy", show: false },
    petStatus: { value: "Healthy", show: false },
    breed: { value: "Labrador", show: false },
    petColor: { value: "Brown", show: false },
    location: { value: "New York", show: false },
    reportedBy: { value: "Admin", show: false },
    reportedOn: { value: "2025-07-11", show: false },
    date: { value: "2025-07-11", show: false },
    donorName: { value: "Jane Smith", show: true },
    amount: { value: "$50", show: false },
    campaign: { value: "Save the pets", show: false },
    type: { value: "One-time", show: false },
    donorstatus: { value: "false", show: false },
    totalAmmount: { value: "12345", show: true },
    lastDonation: { value: "jul 6,2025", show: true },
    recurring: { value: "true", show: true },
    campaignName: { value: "12345", show: false },
    targetAmount: { value: "12345", show: false },
    raisedSoFar: { value: "12345", show: false },
    donors: { value: "12345", show: false },
    campaignStatus: { value: "12345", show: false },
    progress: { value: "12345", show: false },
  },
   {
    user: { value: "John Doe", show: false },
    details: { value: "Some details", show: false },
    time: { value: "12:00 PM", show: false },
    activity: { value: "Logged in", show: false },
    status: { value: "true", show: false },
    emial: { value: "john@example.com", show: true },
    joinedOn: { value: "2025-07-11", show: false },
    reports: { value: "2", show: false },
    recentReports: { value: "2 hours ago", show: false },
    pets: { value: "Dog", show: false },
    petsName: { value: "Buddy", show: false },
    petStatus: { value: "Healthy", show: false },
    breed: { value: "Labrador", show: false },
    petColor: { value: "Brown", show: false },
    location: { value: "New York", show: false },
    reportedBy: { value: "Admin", show: false },
    reportedOn: { value: "2025-07-11", show: false },
    date: { value: "2025-07-11", show: false },
    donorName: { value: "Jane Smith", show: true },
    amount: { value: "$50", show: false },
    campaign: { value: "Save the pets", show: false },
    type: { value: "One-time", show: false },
    donorstatus: { value: "false", show: false },
    totalAmmount: { value: "12345", show: true },
    lastDonation: { value: "jul 6,2025", show: true },
    recurring: { value: "12345", show: true },
    campaignName: { value: "12345", show: false },
    targetAmount: { value: "12345", show: false },
    raisedSoFar: { value: "12345", show: false },
    donors: { value: "12345", show: false },
    campaignStatus: { value: "12345", show: false },
    progress: { value: "12345", show: false },
  },
   {
    user: { value: "John Doe", show: false },
    details: { value: "Some details", show: false },
    time: { value: "12:00 PM", show: false },
    activity: { value: "Logged in", show: false },
    status: { value: "true", show: false },
    emial: { value: "john@example.com", show: true },
    joinedOn: { value: "2025-07-11", show: false },
    reports: { value: "2", show: false },
    recentReports: { value: "2 hours ago", show: false },
    pets: { value: "Dog", show: false },
    petsName: { value: "Buddy", show: false },
    petStatus: { value: "Healthy", show: false },
    breed: { value: "Labrador", show: false },
    petColor: { value: "Brown", show: false },
    location: { value: "New York", show: false },
    reportedBy: { value: "Admin", show: false },
    reportedOn: { value: "2025-07-11", show: false },
    date: { value: "2025-07-11", show: false },
    donorName: { value: "Jane Smith", show: true },
    amount: { value: "$50", show: false },
    campaign: { value: "Save the pets", show: false },
    type: { value: "One-time", show: false },
    donorstatus: { value: "false", show: false },
    totalAmmount: { value: "12345", show: true },
    lastDonation: { value: "jul 6,2025", show: true },
    recurring: { value: "true", show: true },
    campaignName: { value: "12345", show: false },
    targetAmount: { value: "12345", show: false },
    raisedSoFar: { value: "12345", show: false },
    donors: { value: "12345", show: false },
    campaignStatus: { value: "12345", show: false },
    progress: { value: "12345", show: false },
  },
   {
    user: { value: "John Doe", show: false },
    details: { value: "Some details", show: false },
    time: { value: "12:00 PM", show: false },
    activity: { value: "Logged in", show: false },
    status: { value: "true", show: false },
    emial: { value: "john@example.com", show: true },
    joinedOn: { value: "2025-07-11", show: false },
    reports: { value: "2", show: false },
    recentReports: { value: "2 hours ago", show: false },
    pets: { value: "Dog", show: false },
    petsName: { value: "Buddy", show: false },
    petStatus: { value: "Healthy", show: false },
    breed: { value: "Labrador", show: false },
    petColor: { value: "Brown", show: false },
    location: { value: "New York", show: false },
    reportedBy: { value: "Admin", show: false },
    reportedOn: { value: "2025-07-11", show: false },
    date: { value: "2025-07-11", show: false },
    donorName: { value: "Jane Smith", show: true },
    amount: { value: "$50", show: false },
    campaign: { value: "Save the pets", show: false },
    type: { value: "One-time", show: false },
    donorstatus: { value: "false", show: false },
    totalAmmount: { value: "12345", show: true },
    lastDonation: { value: "jul 6,2025", show: true },
    recurring: { value: "12345", show: true },
    campaignName: { value: "12345", show: false },
    targetAmount: { value: "12345", show: false },
    raisedSoFar: { value: "12345", show: false },
    donors: { value: "12345", show: false },
    campaignStatus: { value: "12345", show: false },
    progress: { value: "12345", show: false },
  },
   {
    user: { value: "John Doe", show: false },
    details: { value: "Some details", show: false },
    time: { value: "12:00 PM", show: false },
    activity: { value: "Logged in", show: false },
    status: { value: "true", show: false },
    emial: { value: "john@example.com", show: true },
    joinedOn: { value: "2025-07-11", show: false },
    reports: { value: "2", show: false },
    recentReports: { value: "2 hours ago", show: false },
    pets: { value: "Dog", show: false },
    petsName: { value: "Buddy", show: false },
    petStatus: { value: "Healthy", show: false },
    breed: { value: "Labrador", show: false },
    petColor: { value: "Brown", show: false },
    location: { value: "New York", show: false },
    reportedBy: { value: "Admin", show: false },
    reportedOn: { value: "2025-07-11", show: false },
    date: { value: "2025-07-11", show: false },
    donorName: { value: "Jane Smith", show: true },
    amount: { value: "$50", show: false },
    campaign: { value: "Save the pets", show: false },
    type: { value: "One-time", show: false },
    donorstatus: { value: "false", show: false },
    totalAmmount: { value: "12345", show: true },
    lastDonation: { value: "jul 6,2025", show: true },
    recurring: { value: "12345", show: true },
    campaignName: { value: "12345", show: false },
    targetAmount: { value: "12345", show: false },
    raisedSoFar: { value: "12345", show: false },
    donors: { value: "12345", show: false },
    campaignStatus: { value: "12345", show: false },
    progress: { value: "12345", show: false },
  },
   {
    user: { value: "John Doe", show: false },
    details: { value: "Some details", show: false },
    time: { value: "12:00 PM", show: false },
    activity: { value: "Logged in", show: false },
    status: { value: "true", show: false },
    emial: { value: "john@example.com", show: true },
    joinedOn: { value: "2025-07-11", show: false },
    reports: { value: "2", show: false },
    recentReports: { value: "2 hours ago", show: false },
    pets: { value: "Dog", show: false },
    petsName: { value: "Buddy", show: false },
    petStatus: { value: "Healthy", show: false },
    breed: { value: "Labrador", show: false },
    petColor: { value: "Brown", show: false },
    location: { value: "New York", show: false },
    reportedBy: { value: "Admin", show: false },
    reportedOn: { value: "2025-07-11", show: false },
    date: { value: "2025-07-11", show: false },
    donorName: { value: "Jane Smith", show: true },
    amount: { value: "$50", show: false },
    campaign: { value: "Save the pets", show: false },
    type: { value: "One-time", show: false },
    donorstatus: { value: "false", show: false },
    totalAmmount: { value: "12345", show: true },
    lastDonation: { value: "jul 6,2025", show: true },
    recurring: { value: "true", show: true },
    campaignName: { value: "12345", show: false },
    targetAmount: { value: "12345", show: false },
    raisedSoFar: { value: "12345", show: false },
    donors: { value: "12345", show: false },
    campaignStatus: { value: "12345", show: false },
    progress: { value: "12345", show: false },
  },
   {
    user: { value: "John Doe", show: false },
    details: { value: "Some details", show: false },
    time: { value: "12:00 PM", show: false },
    activity: { value: "Logged in", show: false },
    status: { value: "true", show: false },
    emial: { value: "john@example.com", show: true },
    joinedOn: { value: "2025-07-11", show: false },
    reports: { value: "2", show: false },
    recentReports: { value: "2 hours ago", show: false },
    pets: { value: "Dog", show: false },
    petsName: { value: "Buddy", show: false },
    petStatus: { value: "Healthy", show: false },
    breed: { value: "Labrador", show: false },
    petColor: { value: "Brown", show: false },
    location: { value: "New York", show: false },
    reportedBy: { value: "Admin", show: false },
    reportedOn: { value: "2025-07-11", show: false },
    date: { value: "2025-07-11", show: false },
    donorName: { value: "Jane Smith", show: true },
    amount: { value: "$50", show: false },
    campaign: { value: "Save the pets", show: false },
    type: { value: "One-time", show: false },
    donorstatus: { value: "false", show: false },
    totalAmmount: { value: "12345", show: true },
    lastDonation: { value: "jul 6,2025", show: true },
    recurring: { value: "true", show: true },
    campaignName: { value: "12345", show: false },
    targetAmount: { value: "12345", show: false },
    raisedSoFar: { value: "12345", show: false },
    donors: { value: "12345", show: false },
    campaignStatus: { value: "12345", show: false },
    progress: { value: "12345", show: false },
  },
   {
    user: { value: "John Doe", show: false },
    details: { value: "Some details", show: false },
    time: { value: "12:00 PM", show: false },
    activity: { value: "Logged in", show: false },
    status: { value: "true", show: false },
    emial: { value: "john@example.com", show: true },
    joinedOn: { value: "2025-07-11", show: false },
    reports: { value: "2", show: false },
    recentReports: { value: "2 hours ago", show: false },
    pets: { value: "Dog", show: false },
    petsName: { value: "Buddy", show: false },
    petStatus: { value: "Healthy", show: false },
    breed: { value: "Labrador", show: false },
    petColor: { value: "Brown", show: false },
    location: { value: "New York", show: false },
    reportedBy: { value: "Admin", show: false },
    reportedOn: { value: "2025-07-11", show: false },
    date: { value: "2025-07-11", show: false },
    donorName: { value: "Jane Smith", show: true },
    amount: { value: "$50", show: false },
    campaign: { value: "Save the pets", show: false },
    type: { value: "One-time", show: false },
    donorstatus: { value: "false", show: false },
    totalAmmount: { value: "12345", show: true },
    lastDonation: { value: "jul 6,2025", show: true },
    recurring: { value: "12345", show: true },
    campaignName: { value: "12345", show: false },
    targetAmount: { value: "12345", show: false },
    raisedSoFar: { value: "12345", show: false },
    donors: { value: "12345", show: false },
    campaignStatus: { value: "12345", show: false },
    progress: { value: "12345", show: false },
  },
   {
    user: { value: "John Doe", show: false },
    details: { value: "Some details", show: false },
    time: { value: "12:00 PM", show: false },
    activity: { value: "Logged in", show: false },
    status: { value: "true", show: false },
    emial: { value: "john@example.com", show: true },
    joinedOn: { value: "2025-07-11", show: false },
    reports: { value: "2", show: false },
    recentReports: { value: "2 hours ago", show: false },
    pets: { value: "Dog", show: false },
    petsName: { value: "Buddy", show: false },
    petStatus: { value: "Healthy", show: false },
    breed: { value: "Labrador", show: false },
    petColor: { value: "Brown", show: false },
    location: { value: "New York", show: false },
    reportedBy: { value: "Admin", show: false },
    reportedOn: { value: "2025-07-11", show: false },
    date: { value: "2025-07-11", show: false },
    donorName: { value: "Jane Smith", show: true },
    amount: { value: "$50", show: false },
    campaign: { value: "Save the pets", show: false },
    type: { value: "One-time", show: false },
    donorstatus: { value: "false", show: false },
    totalAmmount: { value: "12345", show: true },
    lastDonation: { value: "jul 6,2025", show: true },
    recurring: { value: "true", show: true },
    campaignName: { value: "12345", show: false },
    targetAmount: { value: "12345", show: false },
    raisedSoFar: { value: "12345", show: false },
    donors: { value: "12345", show: false },
    campaignStatus: { value: "12345", show: false },
    progress: { value: "12345", show: false },
  },
   {
    user: { value: "John Doe", show: false },
    details: { value: "Some details", show: false },
    time: { value: "12:00 PM", show: false },
    activity: { value: "Logged in", show: false },
    status: { value: "true", show: false },
    emial: { value: "john@example.com", show: true },
    joinedOn: { value: "2025-07-11", show: false },
    reports: { value: "2", show: false },
    recentReports: { value: "2 hours ago", show: false },
    pets: { value: "Dog", show: false },
    petsName: { value: "Buddy", show: false },
    petStatus: { value: "Healthy", show: false },
    breed: { value: "Labrador", show: false },
    petColor: { value: "Brown", show: false },
    location: { value: "New York", show: false },
    reportedBy: { value: "Admin", show: false },
    reportedOn: { value: "2025-07-11", show: false },
    date: { value: "2025-07-11", show: false },
    donorName: { value: "Jane Smith", show: true },
    amount: { value: "$50", show: false },
    campaign: { value: "Save the pets", show: false },
    type: { value: "One-time", show: false },
    donorstatus: { value: "false", show: false },
    totalAmmount: { value: "12345", show: true },
    lastDonation: { value: "jul 6,2025", show: true },
    recurring: { value: "12345", show: true },
    campaignName: { value: "12345", show: false },
    targetAmount: { value: "12345", show: false },
    raisedSoFar: { value: "12345", show: false },
    donors: { value: "12345", show: false },
    campaignStatus: { value: "12345", show: false },
    progress: { value: "12345", show: false },
  },
 
]
export default DonorDirectryTableData