
const PetListingTableData = [

      {
    user: { value: "John Doe", show: false },
    details: { value: "Some details", show: false },
    time: { value: "12:00 PM", show: false },
    activity: { value: "Logged in", show: false },
    status: { value: "true", show: false },
    emial: { value: "john@example.com", show: false },
    joinedOn: { value: "2025-07-11", show: false },
    reports: { value: "2", show: false },
    recentReports: { value: "2 hours ago", show: false },
    pets: { value: "Dog", show: true },
    petsName: { value: "Huddy", show: true },
    petStatus: { value: "Healthy", show: true },
    breed: { value: "Labrador", show: true },
    petColor: { value: "Brown", show: true },
    location: { value: "New York", show: true },
    reportedBy: { value: "Admin", show: true },
    reportedOn: { value: "2025-07-11", show: true },
    date: { value: "2025-07-11", show: false },
    donorName: { value: "Jane Smith", show: false },
    amount: { value: "$50", show: false },
    campaign: { value: "Save the pets", show: false },
    type: { value: "One-time", show: false },
    donorstatus: { value: "Confirmed", show: false },
    totalAmmount: { value: "12345", show: false },
    lastDonation: { value: "jul 6,2025", show: false },
    recurring: { value: "12345", show: false },
    campaignName: { value: "12345", show: false },
    targetAmount: { value: "12345", show: false },
    raisedSoFar: { value: "12345", show: false },
    donors: { value: "12345", show: false },
    campaignStatus: { value: "12345", show: false },
    progress: { value: "12345", show: false },
  },
    {
    user: { value: "Scott Boland", show: false },
    details: { value: "Some details", show: false },
    time: { value: "12:00 PM", show: false },
    activity: { value: "Logged in", show: false },
    status: { value: "true", show: false },
    emial: { value: "john@example.com", show: false },
    joinedOn: { value: "2025-07-11", show: false },
    reports: { value: "2", show: false },
    recentReports: { value: "2 hours ago", show: false },
    pets: { value: "Dog", show: true },
    petsName: { value: "Buddy", show: true },
    petStatus: { value: "Healthy", show: true },
    breed: { value: "Labrador", show: true },
    petColor: { value: "Brown", show: true },
    location: { value: "New York", show: true },
    reportedBy: { value: "Admin", show: true },
    reportedOn: { value: "2025-07-11", show: true },
    date: { value: "2025-07-11", show: false },
    donorName: { value: "Jane Smith", show: false },
    amount: { value: "$50", show: false },
    campaign: { value: "Save the pets", show: false },
    type: { value: "One-time", show: false },
    donorstatus: { value: "Confirmed", show: false },
    totalAmmount: { value: "12345", show: false },
    lastDonation: { value: "jul 6,2025", show: false },
    recurring: { value: "12345", show: false },
    campaignName: { value: "12345", show: false },
    targetAmount: { value: "12345", show: false },
    raisedSoFar: { value: "12345", show: false },
    donors: { value: "12345", show: false },
    campaignStatus: { value: "12345", show: false },
    progress: { value: "12345", show: false },
  },
    {
    user: { value: "Rowman Powall", show: false },
    details: { value: "Some details", show: false },
    time: { value: "12:00 PM", show: false },
    activity: { value: "Logged in", show: false },
    status: { value: "true", show: false },
    emial: { value: "john@example.com", show: false },
    joinedOn: { value: "2025-07-11", show: false },
    reports: { value: "2", show: false },
    recentReports: { value: "2 hours ago", show: false },
    pets: { value: "Dog", show: true },
    petsName: { value: "Liger", show: true },
    petStatus: { value: "Healthy", show: true },
    breed: { value: "Labrador", show: true },
    petColor: { value: "Brown", show: true },
    location: { value: "New York", show: true },
    reportedBy: { value: "Admin", show: true },
    reportedOn: { value: "2025-07-11", show: true },
    date: { value: "2025-07-11", show: false },
    donorName: { value: "Jane Smith", show: false },
    amount: { value: "$50", show: false },
    campaign: { value: "Save the pets", show: false },
    type: { value: "One-time", show: false },
    donorstatus: { value: "Confirmed", show: false },
    totalAmmount: { value: "12345", show: false },
    lastDonation: { value: "jul 6,2025", show: false },
    recurring: { value: "12345", show: false },
    campaignName: { value: "12345", show: false },
    targetAmount: { value: "12345", show: false },
    raisedSoFar: { value: "12345", show: false },
    donors: { value: "12345", show: false },
    campaignStatus: { value: "12345", show: false },
    progress: { value: "12345", show: false },
  },
    {
    user: { value: "Mitchel Owen", show: false },
    details: { value: "Some details", show: false },
    time: { value: "12:00 PM", show: false },
    activity: { value: "Logged in", show: false },
    status: { value: "true", show: false },
    emial: { value: "john@example.com", show: false },
    joinedOn: { value: "2025-07-11", show: false },
    reports: { value: "2", show: false },
    recentReports: { value: "2 hours ago", show: false },
    pets: { value: "Dog", show: true },
    petsName: { value: "Neon", show: true },
    petStatus: { value: "Healthy", show: true },
    breed: { value: "Labrador", show: true },
    petColor: { value: "Brown", show: true },
    location: { value: "New York", show: true },
    reportedBy: { value: "Admin", show: true },
    reportedOn: { value: "2025-07-11", show: true },
    date: { value: "2025-07-11", show: false },
    donorName: { value: "Jane Smith", show: false },
    amount: { value: "$50", show: false },
    campaign: { value: "Save the pets", show: false },
    type: { value: "One-time", show: false },
    donorstatus: { value: "Confirmed", show: false },
    totalAmmount: { value: "12345", show: false },
    lastDonation: { value: "jul 6,2025", show: false },
    recurring: { value: "12345", show: false },
    campaignName: { value: "12345", show: false },
    targetAmount: { value: "12345", show: false },
    raisedSoFar: { value: "12345", show: false },
    donors: { value: "12345", show: false },
    campaignStatus: { value: "12345", show: false },
    progress: { value: "12345", show: false },
  },
    {
    user: { value: "Alex Carey", show: false },
    details: { value: "Some details", show: false },
    time: { value: "12:00 PM", show: false },
    activity: { value: "Logged in", show: false },
    status: { value: "true", show: false },
    emial: { value: "john@example.com", show: false },
    joinedOn: { value: "2025-07-11", show: false },
    reports: { value: "2", show: false },
    recentReports: { value: "2 hours ago", show: false },
    pets: { value: "Dog", show: true },
    petsName: { value: "Brown", show: true },
    petStatus: { value: "Healthy", show: true },
    breed: { value: "Labrador", show: true },
    petColor: { value: "Brown", show: true },
    location: { value: "New York", show: true },
    reportedBy: { value: "Admin", show: true },
    reportedOn: { value: "2025-07-11", show: true },
    date: { value: "2025-07-11", show: false },
    donorName: { value: "Jane Smith", show: false },
    amount: { value: "$50", show: false },
    campaign: { value: "Save the pets", show: false },
    type: { value: "One-time", show: false },
    donorstatus: { value: "Confirmed", show: false },
    totalAmmount: { value: "12345", show: false },
    lastDonation: { value: "jul 6,2025", show: false },
    recurring: { value: "12345", show: false },
    campaignName: { value: "12345", show: false },
    targetAmount: { value: "12345", show: false },
    raisedSoFar: { value: "12345", show: false },
    donors: { value: "12345", show: false },
    campaignStatus: { value: "12345", show: false },
    progress: { value: "12345", show: false },
  },
    {
    user: { value: "Joe Root", show: false },
    details: { value: "Some details", show: false },
    time: { value: "12:00 PM", show: false },
    activity: { value: "Logged in", show: false },
    status: { value: "true", show: false },
    emial: { value: "john@example.com", show: false },
    joinedOn: { value: "2025-07-11", show: false },
    reports: { value: "2", show: false },
    recentReports: { value: "2 hours ago", show: false },
    pets: { value: "Dog", show: true },
    petsName: { value: "Bounce", show: true },
    petStatus: { value: "Healthy", show: true },
    breed: { value: "Labrador", show: true },
    petColor: { value: "Brown", show: true },
    location: { value: "New York", show: true },
    reportedBy: { value: "Admin", show: true },
    reportedOn: { value: "2025-07-11", show: true },
    date: { value: "2025-07-11", show: false },
    donorName: { value: "Jane Smith", show: false },
    amount: { value: "$50", show: false },
    campaign: { value: "Save the pets", show: false },
    type: { value: "One-time", show: false },
    donorstatus: { value: "Confirmed", show: false },
    totalAmmount: { value: "12345", show: false },
    lastDonation: { value: "jul 6,2025", show: false },
    recurring: { value: "12345", show: false },
    campaignName: { value: "12345", show: false },
    targetAmount: { value: "12345", show: false },
    raisedSoFar: { value: "12345", show: false },
    donors: { value: "12345", show: false },
    campaignStatus: { value: "12345", show: false },
    progress: { value: "12345", show: false },
  },
    {
    user: { value: "Alex Hales", show: false },
    details: { value: "Some details", show: false },
    time: { value: "12:00 PM", show: false },
    activity: { value: "Logged in", show: false },
    status: { value: "true", show: false },
    emial: { value: "john@example.com", show: false },
    joinedOn: { value: "2025-07-11", show: false },
    reports: { value: "2", show: false },
    recentReports: { value: "2 hours ago", show: false },
    pets: { value: "Dog", show: true },
    petsName: { value: "Buddy", show: true },
    petStatus: { value: "Healthy", show: true },
    breed: { value: "Labrador", show: true },
    petColor: { value: "Brown", show: true },
    location: { value: "New York", show: true },
    reportedBy: { value: "Admin", show: true },
    reportedOn: { value: "2025-07-11", show: true },
    date: { value: "2025-07-11", show: false },
    donorName: { value: "Jane Smith", show: false },
    amount: { value: "$50", show: false },
    campaign: { value: "Save the pets", show: false },
    type: { value: "One-time", show: false },
    donorstatus: { value: "Confirmed", show: false },
    totalAmmount: { value: "12345", show: false },
    lastDonation: { value: "jul 6,2025", show: false },
    recurring: { value: "12345", show: false },
    campaignName: { value: "12345", show: false },
    targetAmount: { value: "12345", show: false },
    raisedSoFar: { value: "12345", show: false },
    donors: { value: "12345", show: false },
    campaignStatus: { value: "12345", show: false },
    progress: { value: "12345", show: false },
  },
    {
    user: { value: "Steve Smith", show: false },
    details: { value: "Some details", show: false },
    time: { value: "12:00 PM", show: false },
    activity: { value: "Logged in", show: false },
    status: { value: "true", show: false },
    emial: { value: "john@example.com", show: false },
    joinedOn: { value: "2025-07-11", show: false },
    reports: { value: "2", show: false },
    recentReports: { value: "2 hours ago", show: false },
    pets: { value: "Dog", show: true },
    petsName: { value: "Bean", show: true },
    petStatus: { value: "Healthy", show: true },
    breed: { value: "Labrador", show: true },
    petColor: { value: "Brown", show: true },
    location: { value: "New York", show: true },
    reportedBy: { value: "Admin", show: true },
    reportedOn: { value: "2025-07-11", show: true },
    date: { value: "2025-07-11", show: false },
    donorName: { value: "Jane Smith", show: false },
    amount: { value: "$50", show: false },
    campaign: { value: "Save the pets", show: false },
    type: { value: "One-time", show: false },
    donorstatus: { value: "Confirmed", show: false },
    totalAmmount: { value: "12345", show: false },
    lastDonation: { value: "jul 6,2025", show: false },
    recurring: { value: "12345", show: false },
    campaignName: { value: "12345", show: false },
    targetAmount: { value: "12345", show: false },
    raisedSoFar: { value: "12345", show: false },
    donors: { value: "12345", show: false },
    campaignStatus: { value: "12345", show: false },
    progress: { value: "12345", show: false },
  },
    {
    user: { value: "David Warner", show: false },
    details: { value: "Some details", show: false },
    time: { value: "12:00 PM", show: false },
    activity: { value: "Logged in", show: false },
    status: { value: "true", show: false },
    emial: { value: "john@example.com", show: false },
    joinedOn: { value: "2025-07-11", show: false },
    reports: { value: "2", show: false },
    recentReports: { value: "2 hours ago", show: false },
    pets: { value: "Dog", show: true },
    petsName: { value: "Roman", show: true },
    petStatus: { value: "Healthy", show: true },
    breed: { value: "Labrador", show: true },
    petColor: { value: "Brown", show: true },
    location: { value: "New York", show: true },
    reportedBy: { value: "Admin", show: true },
    reportedOn: { value: "2025-07-11", show: true },
    date: { value: "2025-07-11", show: false },
    donorName: { value: "Jane Smith", show: false },
    amount: { value: "$50", show: false },
    campaign: { value: "Save the pets", show: false },
    type: { value: "One-time", show: false },
    donorstatus: { value: "Confirmed", show: false },
    totalAmmount: { value: "12345", show: false },
    lastDonation: { value: "jul 6,2025", show: false },
    recurring: { value: "12345", show: false },
    campaignName: { value: "12345", show: false },
    targetAmount: { value: "12345", show: false },
    raisedSoFar: { value: "12345", show: false },
    donors: { value: "12345", show: false },
    campaignStatus: { value: "12345", show: false },
    progress: { value: "12345", show: false },
  },
    {
    user: { value: "John Smith", show: false },
    details: { value: "Some details", show: false },
    time: { value: "12:00 PM", show: false },
    activity: { value: "Logged in", show: false },
    status: { value: "true", show: false },
    emial: { value: "john@example.com", show: false },
    joinedOn: { value: "2025-07-11", show: false },
    reports: { value: "2", show: false },
    recentReports: { value: "2 hours ago", show: false },
    pets: { value: "Dog", show: true },
    petsName: { value: "Humen", show: true },
    petStatus: { value: "Healthy", show: true },
    breed: { value: "Labrador", show: true },
    petColor: { value: "Brown", show: true },
    location: { value: "New York", show: true },
    reportedBy: { value: "Admin", show: true },
    reportedOn: { value: "2025-07-11", show: true },
    date: { value: "2025-07-11", show: false },
    donorName: { value: "Jane Smith", show: false },
    amount: { value: "$50", show: false },
    campaign: { value: "Save the pets", show: false },
    type: { value: "One-time", show: false },
    donorstatus: { value: "Confirmed", show: false },
    totalAmmount: { value: "12345", show: false },
    lastDonation: { value: "jul 6,2025", show: false },
    recurring: { value: "12345", show: false },
    campaignName: { value: "12345", show: false },
    targetAmount: { value: "12345", show: false },
    raisedSoFar: { value: "12345", show: false },
    donors: { value: "12345", show: false },
    campaignStatus: { value: "12345", show: false },
    progress: { value: "12345", show: false },
  },
]

export default PetListingTableData