import Profileimg from "../assets/Images/profile.png"; 

const UserManagmentTableData  = [
  {
    user: { value: "John Doe", show: true },
    userImg: Profileimg,
    details: { value: "Some details", show: false },
    time: { value: "12:00 PM", show: false },
    activity: { value: "Logged in", show: false },
    status: { value: "true", show: false },
    emial: { value: "john@example.com", show: true },
    joinedOn: { value: "2025-07-11", show: true },
    reports: { value: "2", show: true },
    recentReports: { value: "2 hours ago", show: true },
    pets: { value: "Dog", show: false },
    petsName: { value: "Buddy", show: false },
    petStatus: { value: "Healthy", show: false },
    breed: { value: "Labrador", show: false },
    petColor: { value: "Brown", show: false },
    location: { value: "New York", show: false },
    reportedBy: { value: "Admin", show: false },
    reportedOn: { value: "2025-07-11", show: false },
    date: { value: "2025-07-11", show: false },
    donorName: { value: "Jane Smith", show: false },
    amount: { value: "$50", show: false },
    campaign: { value: "Save the pets", show: false },
    type: { value: "One-time", show: false },
    donorstatus: { value: "Confirmed", show: false },
    totalAmmount: { value: "12345", show: false },
    lastDonation: { value: "jul 6,2025", show: false },
    recurring: { value: "12345", show: false },
    campaignName: { value: "12345", show: false },
    targetAmount: { value: "12345", show: false },
    raisedSoFar: { value: "12345", show: false },
    donors: { value: "12345", show: false },
    campaignStatus: { value: "12345", show: false },
    progress: { value: "12345", show: false },
  },
  {
    user: { value: "Alice Smith", show: true },
    userImg: Profileimg,
    details: { value: "Details here", show: false },
    time: { value: "1:30 PM", show: false },
    activity: { value: "Signed up", show: false },
    status: { value: "false", show: false },
    emial: { value: "alice@example.com", show: true },
    joinedOn: { value: "2025-07-10", show: true },
    reports: { value: "3", show: true },
    recentReports: { value: "1 hour ago", show: true },
    pets: { value: "Cat", show: false },
    petsName: { value: "Whiskers", show: false },
    petStatus: { value: "Active", show: false },
    breed: { value: "Siamese", show: false },
    petColor: { value: "White", show: false },
    location: { value: "Los Angeles", show: false },
    reportedBy: { value: "User", show: false },
    reportedOn: { value: "2025-07-10", show: false },
    date: { value: "2025-07-10", show: false },
    donorName: { value: "Tom Lee", show: false },
    amount: { value: "$100", show: false },
    campaign: { value: "Feed the cats", show: false },
    type: { value: "Monthly", show: false },
    donorstatus: { value: "Pending", show: false },
    totalAmmount: { value: "12345", show: false },
    lastDonation: { value: "jul 6,2025", show: false },
    recurring: { value: "12345", show: false },
    campaignName: { value: "12345", show: false },
    targetAmount: { value: "12345", show: false },
    raisedSoFar: { value: "12345", show: false },
    donors: { value: "12345", show: false },
    campaignStatus: { value: "12345", show: false },
    progress: { value: "12345", show: false },
  },
  {
    user: { value: "Michael Brown", show: true },
    userImg: Profileimg,
    details: { value: "", show: false },
    time: { value: "", show: false },
    activity: { value: "", show: false },
    status: { value: "", show: false },
    emial: { value: "michael@example.com", show: true },
    joinedOn: { value: "2025-07-09", show: true },
    reports: { value: "1", show: true },
    recentReports: { value: "3 hours ago", show: true },
    pets: { value: "", show: false },
    petsName: { value: "", show: false },
    petStatus: { value: "", show: false },
    breed: { value: "", show: false },
    petColor: { value: "", show: false },
    location: { value: "", show: false },
    reportedBy: { value: "", show: false },
    reportedOn: { value: "", show: false },
    date: { value: "", show: false },
    donorName: { value: "", show: false },
    amount: { value: "", show: false },
    campaign: { value: "", show: false },
    type: { value: "", show: false },
    donorstatus: { value: "", show: false },
    totalAmmount: { value: "12345", show: false },
    lastDonation: { value: "jul 6,2025", show: false },
    recurring: { value: "12345", show: false },
    campaignName: { value: "12345", show: false },
    targetAmount: { value: "12345", show: false },
    raisedSoFar: { value: "12345", show: false },
    donors: { value: "12345", show: false },
    campaignStatus: { value: "12345", show: false },
    progress: { value: "12345", show: false },
  },
  {
    user: { value: "Emily Johnson", show: true },
    userImg: Profileimg,
    details: { value: "", show: false },
    time: { value: "", show: false },
    activity: { value: "", show: false },
    status: { value: "", show: false },
    emial: { value: "emily@example.com", show: true },
    joinedOn: { value: "2025-07-08", show: true },
    reports: { value: "0", show: true },
    recentReports: { value: "5 hours ago", show: true },
    pets: { value: "", show: false },
    petsName: { value: "", show: false },
    petStatus: { value: "", show: false },
    breed: { value: "", show: false },
    petColor: { value: "", show: false },
    location: { value: "", show: false },
    reportedBy: { value: "", show: false },
    reportedOn: { value: "", show: false },
    date: { value: "", show: false },
    donorName: { value: "", show: false },
    amount: { value: "", show: false },
    campaign: { value: "", show: false },
    type: { value: "", show: false },
    donorstatus: { value: "", show: false },
    totalAmmount: { value: "12345", show: false },
    lastDonation: { value: "jul 6,2025", show: false },
    recurring: { value: "12345", show: false },
    campaignName: { value: "12345", show: false },
    targetAmount: { value: "12345", show: false },
    raisedSoFar: { value: "12345", show: false },
    donors: { value: "12345", show: false },
    campaignStatus: { value: "12345", show: false },
    progress: { value: "12345", show: false },
  },
  {
    user: { value: "David Wilson", show: true },
    userImg: Profileimg,
    details: { value: "", show: false },
    time: { value: "", show: false },
    activity: { value: "", show: false },
    status: { value: "", show: false },
    emial: { value: "david@example.com", show: true },
    joinedOn: { value: "2025-07-07", show: true },
    reports: { value: "4", show: true },
    recentReports: { value: "4 hours ago", show: true },
    pets: { value: "", show: false },
    petsName: { value: "", show: false },
    petStatus: { value: "", show: false },
    breed: { value: "", show: false },
    petColor: { value: "", show: false },
    location: { value: "", show: false },
    reportedBy: { value: "", show: false },
    reportedOn: { value: "", show: false },
    date: { value: "", show: false },
    donorName: { value: "", show: false },
    amount: { value: "", show: false },
    campaign: { value: "", show: false },
    type: { value: "", show: false },
    donorstatus: { value: "", show: false },
    totalAmmount: { value: "12345", show: false },
    lastDonation: { value: "jul 6,2025", show: false },
    recurring: { value: "12345", show: false },
    campaignName: { value: "12345", show: false },
    targetAmount: { value: "12345", show: false },
    raisedSoFar: { value: "12345", show: false },
    donors: { value: "12345", show: false },
    campaignStatus: { value: "12345", show: false },
    progress: { value: "12345", show: false },
  },

  {
    user: { value: "Sarah Lee", show: true },
    userImg: Profileimg,
    details: { value: "", show: false },
    time: { value: "", show: false },
    activity: { value: "", show: false },
    status: { value: "", show: false },
    emial: { value: "sarah@example.com", show: true },
    joinedOn: { value: "2025-07-06", show: true },
    reports: { value: "2", show: true },
    recentReports: { value: "6 hours ago", show: true },
    pets: { value: "", show: false },
    petsName: { value: "", show: false },
    petStatus: { value: "", show: false },
    breed: { value: "", show: false },
    petColor: { value: "", show: false },
    location: { value: "", show: false },
    reportedBy: { value: "", show: false },
    reportedOn: { value: "", show: false },
    date: { value: "", show: false },
    donorName: { value: "", show: false },
    amount: { value: "", show: false },
    campaign: { value: "", show: false },
    type: { value: "", show: false },
    donorstatus: { value: "", show: false },
    totalAmmount: { value: "12345", show: false },
    lastDonation: { value: "jul 6,2025", show: false },
    recurring: { value: "12345", show: false },
    campaignName: { value: "12345", show: false },
    targetAmount: { value: "12345", show: false },
    raisedSoFar: { value: "12345", show: false },
    donors: { value: "12345", show: false },
    campaignStatus: { value: "12345", show: false },
    progress: { value: "12345", show: false },
  },
  {
    user: { value: "James Kim", show: true },
    userImg: Profileimg,
    details: { value: "", show: false },
    time: { value: "", show: false },
    activity: { value: "", show: false },
    status: { value: "", show: false },
    emial: { value: "james@example.com", show: true },
    joinedOn: { value: "2025-07-05", show: true },
    reports: { value: "1", show: true },
    recentReports: { value: "7 hours ago", show: true },
    pets: { value: "", show: false },
    petsName: { value: "", show: false },
    petStatus: { value: "", show: false },
    breed: { value: "", show: false },
    petColor: { value: "", show: false },
    location: { value: "", show: false },
    reportedBy: { value: "", show: false },
    reportedOn: { value: "", show: false },
    date: { value: "", show: false },
    donorName: { value: "", show: false },
    amount: { value: "", show: false },
    campaign: { value: "", show: false },
    type: { value: "", show: false },
    donorstatus: { value: "", show: false },
    totalAmmount: { value: "12345", show: false },
    lastDonation: { value: "jul 6,2025", show: false },
    recurring: { value: "12345", show: false },
    campaignName: { value: "12345", show: false },
    targetAmount: { value: "12345", show: false },
    raisedSoFar: { value: "12345", show: false },
    donors: { value: "12345", show: false },
    campaignStatus: { value: "12345", show: false },
    progress: { value: "12345", show: false },
  },
  {
    user: { value: "Linda Park", show: true },
    userImg: Profileimg,
    details: { value: "", show: false },
    time: { value: "", show: false },
    activity: { value: "", show: false },
    status: { value: "", show: false },
    emial: { value: "linda@example.com", show: true },
    joinedOn: { value: "2025-07-04", show: true },
    reports: { value: "3", show: true },
    recentReports: { value: "8 hours ago", show: true },
    pets: { value: "", show: false },
    petsName: { value: "", show: false },
    petStatus: { value: "", show: false },
    breed: { value: "", show: false },
    petColor: { value: "", show: false },
    location: { value: "", show: false },
    reportedBy: { value: "", show: false },
    reportedOn: { value: "", show: false },
    date: { value: "", show: false },
    donorName: { value: "", show: false },
    amount: { value: "", show: false },
    campaign: { value: "", show: false },
    type: { value: "", show: false },
    donorstatus: { value: "", show: false },
    totalAmmount: { value: "12345", show: false },
    lastDonation: { value: "jul 6,2025", show: false },
    recurring: { value: "12345", show: false },
    campaignName: { value: "12345", show: false },
    targetAmount: { value: "12345", show: false },
    raisedSoFar: { value: "12345", show: false },
    donors: { value: "12345", show: false },
    campaignStatus: { value: "12345", show: false },
    progress: { value: "12345", show: false },
  },
  {
    user: { value: "Robert Scott", show: true },
    userImg: Profileimg,
    details: { value: "", show: false },
    time: { value: "", show: false },
    activity: { value: "", show: false },
    status: { value: "", show: false },
    emial: { value: "robert@example.com", show: true },
    joinedOn: { value: "2025-07-03", show: true },
    reports: { value: "5", show: true },
    recentReports: { value: "9 hours ago", show: true },
    pets: { value: "", show: false },
    petsName: { value: "", show: false },
    petStatus: { value: "", show: false },
    breed: { value: "", show: false },
    petColor: { value: "", show: false },
    location: { value: "", show: false },
    reportedBy: { value: "", show: false },
    reportedOn: { value: "", show: false },
    date: { value: "", show: false },
    donorName: { value: "", show: false },
    amount: { value: "", show: false },
    campaign: { value: "", show: false },
    type: { value: "", show: false },
    donorstatus: { value: "", show: false },
    totalAmmount: { value: "12345", show: false },
    lastDonation: { value: "jul 6,2025", show: false },
    recurring: { value: "12345", show: false },
    campaignName: { value: "12345", show: false },
    targetAmount: { value: "12345", show: false },
    raisedSoFar: { value: "12345", show: false },
    donors: { value: "12345", show: false },
    campaignStatus: { value: "12345", show: false },
    progress: { value: "12345", show: false },
  }
 
 
];

export default UserManagmentTableData;